services:
  postgres-db:
    image: postgres:15
    container_name: risencore-postgres-prod
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  risencore-backend:
    build:
      context: ./backend
    container_name: risencore-backend-prod
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
    volumes:
      - ./logs:/app/logs

  risencore-frontend:
    build:
      context: ./frontend
      target: production
    container_name: risencore-frontend-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - risencore-backend

volumes:
  postgres-data-prod:
